# Generated by Django 2.2.5 on 2019-09-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery')),
                ('for_sale', models.BooleanField(default=False)),
                ('release_date', models.DateField(auto_now_add=True)),
                ('sys_created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
