# Generated by Django 2.2.5 on 2019-09-20 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pukshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='release_date',
            field=models.DateField(),
        ),
    ]
